<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;net10.0</TargetFrameworks>
    <SignAssembly>true</SignAssembly>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\AssemblyWithNoSymbols\AssemblyWithNoSymbols.csproj" />
    <ProjectReference Include="..\DummyAssembly\DummyAssembly.csproj" />
    <ProjectReference Include="..\FodyCommon\FodyCommon.csproj" />
    <ProjectReference Include="..\FodyHelpers\FodyHelpers.csproj" />
    <ProjectReference Include="..\FodyIsolated\FodyIsolated.csproj" />
    <ProjectReference Include="..\FodyTasks\FodyTasks.csproj" />
    <ProjectReference Include="..\SampleWeaver.Fody\SampleWeaver.Fody.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="System.Threading.Tasks" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="TUnit.Core" />
    <PackageReference Include="TUnit.Assertions" />
    <PackageReference Include="TUnit.Engine" />
    <PackageReference Include="Nullable" PrivateAssets="All" />
    <PackageReference Include="Microsoft.Build.Tasks.Core" />
    <PackageReference Include="Verify.TUnit" />
    <PackageReference Include="Newtonsoft.Json" />
  </ItemGroup>
  <ItemGroup Condition="$(TargetFrameworkIdentifier) == '.NETFramework'">
    <Reference Include="Microsoft.Build.Utilities.v4.0" Aliases="msbuild4" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="Fody\NugetConfig*.txt" CopyToOutputDirectory="Always" />
    <Content Include="Fody\Verify\VerifierTests_*.*" CopyToOutputDirectory="Always" />
    <Content Include="Fody\Packages\SampleWeaver.Fody.1.0.0.0\SampleWeaver.Fody.dll" CopyToOutputDirectory="Always" />
    <Content Include="Fody\ProjectWeaversReaderTests\Invalid.txt" />
    <Content Include="Fody\ProjectWeaversReaderTests\*.xml" CopyToOutputDirectory="Always" />
    <Content Include="Fody\ProjectWeaversReaderTests\*.txt" CopyToOutputDirectory="Always" />
  </ItemGroup>
</Project>
