<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net472;net10.0</TargetFrameworks>
    <SignAssembly>true</SignAssembly>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\DummyAssembly\DummyAssembly.csproj" />
    <ProjectReference Include="..\DummyExeAssembly\DummyExeAssembly.csproj" />
    <ProjectReference Include="..\FodyCommon\FodyCommon.csproj" />
    <ProjectReference Include="..\FodyHelpers\FodyHelpers.csproj" />
    <ProjectReference Include="..\FodyIsolated\FodyIsolated.csproj" />
    <ProjectReference Include="..\SampleWeaver.Fody\SampleWeaver.Fody.csproj" />
    <ProjectReference Include="..\cecil\Mono.Cecil.csproj" />
    <ProjectReference Include="..\cecil\rocks\Mono.Cecil.Rocks.csproj" />
    <ProjectReference Include="..\cecil\symbols\pdb\Mono.Cecil.Pdb.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="System.Threading.Tasks" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Build.Tasks.Core" />
    <PackageReference Include="TUnit.Core" />
    <PackageReference Include="TUnit.Assertions" />
    <PackageReference Include="TUnit.Engine" />
    <PackageReference Include="Verify.TUnit" />
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="Nullable" PrivateAssets="All" />
  </ItemGroup>
</Project>
